name: "Xiaomi Hub Proxy"
description: "add-on for xiaomi-hub-proxy integration"
version: "0.0.1"
slug: "xiaomi_hub_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
